FROM python:3.7

# Create a project directory.
RUN mkdir /app
WORKDIR /app

# Install Python dependencies.
COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

# Run your app.
CMD ["wave", "run", "src/app.py"]